title: Cameron Marsh Artwork
url: 
baseurl: 

author: Cameron Marsh

include: ['_pages']

collections_dir: series

collections:
  etching:
    output: true 
  landscape:
    output: true
  figure:
    output: true 
  still_life:
    output: true 

markdown: kramdown
kramdown:
  input: GFM